name: default

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
  release-snapshot:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checking out the source code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Testing the version
        run: ./gradlew cV
      - name: Publish the snapshot
        run: ./gradlew publish
        env:
          PACKAGE_MASTER: ${{ secrets.PACKAGE_MASTER }}
          PACKAGE_MASTER_PASSWORD: ${{ secrets.PACKAGE_MASTER_PASSWORD }}
