name: master-release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User
        run: |
          git config --local user.email "bot@electricdog.io"
          git config --local user.name "Electric Dog"
      - name: Release
        run: ./gradlew build release -x check
      - name: Publish
        run: ./gradlew publish
        env:
          PACKAGE_MASTER: ${{ secrets.PACKAGE_MASTER }}
          PACKAGE_MASTER_PASSWORD: ${{ secrets.PACKAGE_MASTER_PASSWORD }}